service: ${env:SERVICE_NAME}

plugins:
  - serverless-plugin-scripts
  - serverless-glue

useDotenv: true

package:
  individually: true

custom:
  scripts:
    hooks:
      "package:initialize": npm run zip-libs

provider:
  name: aws
  stage: local
  runtime: python3.9

# Glue Jobs configuration:
# Check the full documentation at https://www.npmjs.com/package/serverless-glue
Glue: ${file(./glue.yml)}

resources:
  - ${file(./resource/GlueResources.yml)}
