services:
  glue-job:
    build: ..
    environment:
      DISABLE_SSL: "true"
    # entrypoint: [ "tail", "-f", "/dev/null" ]
    volumes:
      - ../libs:${WORKDIR}/libs
      - ../jobs:${WORKDIR}/jobs
      - ~/.aws:/home/glue_user/.aws
    env_file:
      - .env
    depends_on:
      - localstack
      # - setup-resources
    networks:
      - aws-glue-boilerplate

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:latest
    ports:
      - "4566:4566" # LocalStack Gateway
      - "4510-4559:4510-4559" # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - PERSISTENCE=${PERSISTENCE-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY-} # only required for Pro
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=s3
    volumes:
      - localstack:${LOCALSTACK_DATA_DIR:-/tmp/}localstack/data
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - aws-glue-boilerplate

  setup-resources:
    build: ..
    entrypoint: /bin/bash
    command: /project/setup-resources.sh
    volumes:
      - ./localstack:/project
    environment:
      - AWS_ACCESS_KEY_ID=dummyaccess
      - AWS_SECRET_ACCESS_KEY=dummysecret
      - AWS_DEFAULT_REGION=us-east-1
    networks:
      - aws-glue-boilerplate
    depends_on:
      - localstack

  postgresql:
    image: postgres:latest
    restart: unless-stopped
    user: postgres
    volumes:
      - ./postgres/initdb.d:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - POSTGRES_USER=${POSTGRES_DB_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - aws-glue-boilerplate

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    volumes:
      - ./pgadmin-bootstrap/:/pgadmin4/bootstrap/
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_SERVER_JSON_FILE: ${PGADMIN_SERVER_JSON_FILE}
    ports:
      - 5050:80
    networks:
      - aws-glue-boilerplate
    depends_on:
      - postgresql

  docdb:
    image: mongo:4
    command: --tlsMode disabled
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DOCUMENTDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DOCUMENTDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${DOCUMENTDB_DATABASE}
      MONGO_NON_ROOT_USERNAME: ${DOCUMENTDB_USERNAME}
      MONGO_NON_ROOT_PASSWORD: ${DOCUMENTDB_PASSWORD}
    volumes:
      - ./docdb/initdb.d:/docker-entrypoint-initdb.d:ro
      - docdb-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo 127.0.0.1:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - aws-glue-boilerplate

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    depends_on:
      - docdb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DOCUMENTDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DOCUMENTDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: docdb
      ME_CONFIG_MONGODB_PORT: 27017
    healthcheck:
      test: wget --quiet --tries=3 --spider http://${DOCUMENTDB_ROOT_USERNAME}:${DOCUMENTDB_ROOT_PASSWORD}@127.0.0.1:8081 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - aws-glue-boilerplate

networks:
  aws-glue-boilerplate:
    driver: "bridge"

volumes:
  localstack:
  postgres-data:
  docdb-data:
