services:
  glue-job:
    build: ..
    environment:
      DISABLE_SSL: "true"
    # command: spark-submit jobs/hello_world.py --JOB_NAME=hello_world
    entrypoint: [ "tail", "-f", "/dev/null" ]
    volumes:
      - ../jobs:/home/glue_user/workspace/jobs
      - ../libs:/home/glue_user/workspace/libs
      - ~/.aws:/home/glue_user/.aws
    env_file:
      - .env
    depends_on:
      - localstack
    networks:
      - aws-glue-boilerplate

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - localstack:${LOCALSTACK_DATA_DIR:-/tmp/}localstack/data
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - aws-glue-boilerplate

  setup-resources:
    image: mesosphere/aws-cli:1.14.5
    entrypoint: tail -f /dev/null
    # command: /project/localstack # /setup-resources.sh
    volumes:
      - ./local-dev/localstack:/project
      - ~/.aws:/home/glue_user/.aws
    networks:
      - aws-glue-boilerplate
    depends_on:
      - localstack
    env_file:
      - .env

networks:
  aws-glue-boilerplate:
    driver: "bridge"

volumes:
  localstack:
