---
Resources:
  GlueConnection:
    Type: AWS::Glue::Connection
    Properties:
      CatalogId: !Ref AWS::AccountId
      ConnectionInput:
        ConnectionType: NETWORK
        ConnectionProperties:
          Name: ${self:service}-${sls:stage}-net
          Description: ${self:service}-${sls:stage} Network
          Type: NETWORK
        PhysicalConnectionRequirements:
          AvailabilityZone: ${env:AWS_AVAILABILITY_ZONE}
          SecurityGroupIdList:
            - !Ref GlueSecurityGroup
          SubnetId: ${env:SUBNET_ID}
  GlueAccessLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: ${self:service}-${sls:stage}-logs
  GlueSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: ${self:service}-${sls:stage}-security-group
      GroupDescription: ${self:service}-${sls:stage} Security Group
      SecurityGroupIngress:
        - IpProtocol: -1
          Description: Allow all traffic by default
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: name
          Value: ${self:service}-${sls:stage}-sg
      VpcId: ${env:VPC_ID}
  GlueJobRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /${self:service}-${sls:stage}-JobRole/
      RoleName: ${self:service}-${sls:stage}-JobRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - glue.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: GlueJobPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ec2:DescribeSubnets
                  - ec2:DescribeSecurityGroups
                  - ec2:DescribeVpcEndpoints
                  - ec2:DescribeVpcEndpointServices
                  - ec2:DescribeRouteTables
                  - ec2:CreateNetworkInterface
                Resource:
                  - "*"
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - "arn:aws:logs:*:*:*"
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource:
                  - Fn::Join:
                      - ":"
                      - - "arn:aws:s3"
                        - ""
                        - ""
                        - "${self:service}-${sls:stage}-glue-bucket-deploy/*"
              - Effect: Allow
                Action:
                  - ec2:CreateTags
                  - ec2:DeleteTags
                Resource:
                  - "arn:aws:ec2:*:*:network-interface/*"
                  - "arn:aws:ec2:*:*:security-group/*"
                  - "arn:aws:ec2:*:*:instance/*"
              - Effect: Allow
                Action:
                  - "glue:GetConnection"
                Resource:
                  - Fn::Join:
                      - ":"
                      - - "arn:aws:glue"
                        - Ref: "AWS::Region"
                        - Ref: "AWS::AccountId"
                        - "catalog"
                  - Fn::Join:
                      - ":"
                      - - "arn:aws:glue"
                        - Ref: "AWS::Region"
                        - Ref: "AWS::AccountId"
                        - "connection/*"
              - Effect: "Allow"
                Action:
                  - "ssm:GetParameter"
                Resource:
                  - Fn::Join:
                      - ":"
                      - - "arn:aws:ssm"
                        - Ref: "AWS::Region"
                        - Ref: "AWS::AccountId"
                        - "parameter/*"
              - Effect: "Allow"
                Action:
                  - "secretsmanager:GetSecretValue"
                Resource:
                  - Fn::Join:
                      - ":"
                      - - "arn:aws:secretsmanager"
                        - Ref: "AWS::Region"
                        - Ref: "AWS::AccountId"
                        - "secret"
                        - "*"

Outputs:
  GlueAccessLogsArn:
    Description: Main Job Access Logs Arn
    Value:
      Fn::GetAtt:
        - GlueAccessLogs
        - Arn
  SecurityGroup:
    Description: ${self:service}-${sls:stage} Security Group
    Value: !GetAtt GlueSecurityGroup.GroupId
