name: Black

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install deps
        run: |
          sudo apt update
          sudo apt install -y python3-venv
      - uses: psf/black@stable
