name: Flake8

on: [push, pull_request]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
      - name: Install Flake8 Plugins
        run: python -m pip install flake8-bugbear==22.1.11 flake8-black
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          path: "jobs"
          args: "--config=.flake8"
